title: ArtWalk LA
description: An independent, unofficial map of artist studios in the Lincoln Heights arts district of Los Angeles.
theme: jekyll-theme-minimal
permalink: /:title/
markdown: kramdown
plugins:
  - jekyll-relative-links
relative_links:
  enabled: true
  collections: false
include:
  - privacy.md
  - support.md
exclude:
  - "*.svg"
  - Gemfile*
